using System.Resources;
using System.Reflection;
using System.Runtime.InteropServices;

// Retained only attributes not auto-generated by SDK style project.
[assembly: AssemblyTitle("NDEF Library Windows Extensions")] // simplified
[assembly: AssemblyDescription("Windows extension helpers for NDEF library")]
[assembly: AssemblyCompany("Andreas Jakl")]
[assembly: AssemblyProduct("NdefLibraryUwp")]
[assembly: AssemblyCopyright("Copyright © 2012-2018 Andreas Jakl")]
[assembly: ComVisible(false)]
[assembly: NeutralResourcesLanguage("en")]

