//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NdefDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NdefDemo.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string AboutInstructions {
            get {
                return ResourceManager.GetString("AboutInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This example app demonstrates the NDEF library for Proximity APIs.
        ///
        ///After initializing NFC, you can use the app to subscribe for NDEF messages - tapping a tag will parse four of the NDEF records supported by the NDEF library: URI, MailTo, Smart Poster, LaunchApp.
        ///
        ///You can also write a message to a tag or publish it to another device. Windows Phone can write to NDEF formatted NFC Forum Type 1 - 4 tags. To publish messages, the other device needs to support the standardized SNEP protcol..
        /// </summary>
        public static string AboutInstructionsText {
            get {
                return ResourceManager.GetString("AboutInstructionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NDEF Library.
        /// </summary>
        public static string AboutNdefLibrary {
            get {
                return ResourceManager.GetString("AboutNdefLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://andijakl.github.io/ndef-nfc/.
        /// </summary>
        public static string AboutNdefLibraryUri {
            get {
                return ResourceManager.GetString("AboutNdefLibraryUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install NFC interactor.
        /// </summary>
        public static string AboutNfcInteractor {
            get {
                return ResourceManager.GetString("AboutNfcInteractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zune:navigate?appid={4e1598fe-4885-4e2b-9c69-8d3f882c545b}.
        /// </summary>
        public static string AboutNfcInteractorUri {
            get {
                return ResourceManager.GetString("AboutNfcInteractorUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This simple code example for developers demonstrates how to write NFC code using the NDEF library. You can download the open source library using the NuGet package manager to directly integrate it into your project. For a fully featured tag reader / writer app, install NFC interactor..
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Updates: Twitter.
        /// </summary>
        public static string AboutTwitter {
            get {
                return ResourceManager.GetString("AboutTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/andijakl
        /// </summary>
        public static string AboutTwitterUri {
            get {
                return ResourceManager.GetString("AboutTwitterUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NDEF DEMO.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize NFC.
        /// </summary>
        public static string BtnInitNfc {
            get {
                return ResourceManager.GetString("BtnInitNfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish URI to Devices.
        /// </summary>
        public static string BtnPublishUri {
            get {
                return ResourceManager.GetString("BtnPublishUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Publication.
        /// </summary>
        public static string BtnStopPublication {
            get {
                return ResourceManager.GetString("BtnStopPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Subscription.
        /// </summary>
        public static string BtnStopSubscription {
            get {
                return ResourceManager.GetString("BtnStopSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe for NDEF messages.
        /// </summary>
        public static string BtnSubscribeNdef {
            get {
                return ResourceManager.GetString("BtnSubscribeNdef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Business Card Tag.
        /// </summary>
        public static string BtnWriteBusinessCard {
            get {
                return ResourceManager.GetString("BtnWriteBusinessCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write LaunchApp Tag.
        /// </summary>
        public static string BtnWriteLaunchApp {
            get {
                return ResourceManager.GetString("BtnWriteLaunchApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write MailTo Tag.
        /// </summary>
        public static string BtnWriteMailTo {
            get {
                return ResourceManager.GetString("BtnWriteMailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading first contact from the address book, please wait....
        /// </summary>
        public static string LoadingFirstContact {
            get {
                return ResourceManager.GetString("LoadingFirstContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string PageTitleAbout {
            get {
                return ResourceManager.GetString("PageTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nfc tests.
        /// </summary>
        public static string PageTitleMain {
            get {
                return ResourceManager.GetString("PageTitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing.
        /// </summary>
        public static string Publishing {
            get {
                return ResourceManager.GetString("Publishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the &quot;Initialize NFC&quot; button to start NFC.
        /// </summary>
        public static string StatusAppStartup {
            get {
                return ResourceManager.GetString("StatusAppStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize proximity device.
        /// </summary>
        public static string StatusInitFailed {
            get {
                return ResourceManager.GetString("StatusInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully initialized proximity device.
        /// </summary>
        public static string StatusInitialized {
            get {
                return ResourceManager.GetString("StatusInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launched app with LaunchApp tag. Arguments: &quot;{0}&quot;.
        /// </summary>
        public static string StatusLaunchedFromTag {
            get {
                return ResourceManager.GetString("StatusLaunchedFromTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success: message published!.
        /// </summary>
        public static string StatusMessageWritten {
            get {
                return ResourceManager.GetString("StatusMessageWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped publishing a message.
        /// </summary>
        public static string StatusPublicationStopped {
            get {
                return ResourceManager.GetString("StatusPublicationStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed for NDEF messages (subscription ID: {0}).
        /// </summary>
        public static string StatusSubscribed {
            get {
                return ResourceManager.GetString("StatusSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped subscription for NDEF messages.
        /// </summary>
        public static string StatusSubscriptionStopped {
            get {
                return ResourceManager.GetString("StatusSubscriptionStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag parsed: {0}.
        /// </summary>
        public static string StatusTagParsed {
            get {
                return ResourceManager.GetString("StatusTagParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap a device to write the message (size: {0} bytes, publication ID: {1}).
        /// </summary>
        public static string StatusWriteToDevice {
            get {
                return ResourceManager.GetString("StatusWriteToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap a tag to write the message (size: {0} bytes, publication ID: {1}).
        /// </summary>
        public static string StatusWriteToTag {
            get {
                return ResourceManager.GetString("StatusWriteToTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string Subscriptions {
            get {
                return ResourceManager.GetString("Subscriptions", resourceCulture);
            }
        }
    }
}
